'use strict';

const gulp = require('gulp');

const init = require('./task/init');
const user = require('./task/user');
const startApi = require('./task/start-api');
const startDashboard = require('./task/start-dashboard');
const stopApi = require('./task/stop-api');
const stopDashboard = require('./task/stop-dashboard');
const sync = require('./task/sync');
const seed = require('./task/seed');
const devApi = require('./task/dev-api');
const devDashboard = require('./task/dev-dashboard');
const lintJS = require('./task/lint-js');
const lintCSS = require('./task/lint-css');
const unit = require('./task/unit');
const syncTest = require('./task/sync-test');
const seedTest = require('./task/seed-test');
const doc = require('./task/doc');

gulp.task(init);
gulp.task(user);
gulp.task(startApi);
gulp.task(startDashboard);
gulp.task('start', gulp.series('startApi', 'startDashboard'));
gulp.task(stopApi);
gulp.task(stopDashboard);
gulp.task('stop', gulp.series('stopApi', 'stopDashboard'));
gulp.task(sync);
gulp.task(seed);
gulp.task(devApi);
gulp.task(devDashboard);
gulp.task(lintJS);
gulp.task(lintCSS);
gulp.task('lint', gulp.series('lintJS', 'lintCSS'));
gulp.task(syncTest);
gulp.task(seedTest);
gulp.task(unit);
gulp.task('test', gulp.series('lint', 'syncTest', 'seedTest', 'unit'));
gulp.task(doc);
