plugins:
    - ava

rules:
    func-style: off
    max-nested-callbacks: off
    no-magic-numbers: off
    id-length:
        - error
        - exceptions:
            - t
    ava/assertion-message: error
    ava/max-asserts: error
    ava/no-cb-test: off
    ava/no-identical-title: error
    no-ignored-test-files: off
    ava/no-invalid-end: error
    ava/no-only-test: error
    ava/no-skip-assert: error
    ava/no-skip-test: error
    ava/no-statement-after-end: error
    ava/no-todo-test: warn
    ava/no-unknown-modifiers: error
    ava/prefer-power-assert: off
    ava/test-ended: error
    ava/test-title: error
    ava/use-t-well: error
    ava/use-t: error
    ava/use-test: error
    ava/use-true-false: error
